import { createI18n } from 'vue-i18n'

const messages = {
  zh: {
    common: { brand: '简试', product: 'JianShi AI', records: '面试记录', upload: '上传简历', apiSettings: 'API 配置', profile: '个人中心', logout: '退出登录', theme: '切换主题', language: '切换语言', loading: '加载中...', save: '保存', cancel: '取消', delete: '删除', back: '返回', score: '得分', status: '状态', date: '时间', actions: '操作', completed: '已完成', inProgress: '进行中', easy: '简单', medium: '中等', hard: '困难', questions: '题', failed: '加载失败', retry: '重试' },
    auth: { signIn: '登录', signingIn: '登录中...', signUp: '注册', signingUp: '注册中...', welcome: '欢迎回来', createAccount: '创建账号', subtitle: '专注、清晰的 AI 模拟面试', email: '邮箱', password: '密码', emailPlaceholder: '请输入邮箱', passwordPlaceholder: '请输入密码', firstName: '名', lastName: '姓', passwordHint: '至少 8 位，含字母、数字和特殊字符', noAccount: '还没有账号？', hasAccount: '已有账号？', registerNow: '立即注册', signInNow: '去登录', registerSuccess: '注册成功，正在跳转...' },
    dashboard: { eyebrow: 'INTERVIEW WORKSPACE', title: '面试记录', subtitle: '查看进度、继续练习，或回顾每次评估。', start: '开始新面试', emptyTitle: '还没有面试记录', emptyText: '上传简历，开始你的第一次 AI 模拟面试。', difficulty: '难度', questionCount: '题数', score: '得分', continue: '继续面试', report: '查看报告', deleteConfirm: '确定删除这条面试记录吗？删除后无法恢复。', deleteFailed: '删除失败' },
    resume: { eyebrow: 'NEW INTERVIEW', title: '上传简历', subtitle: '提交 PDF 简历，简试会分析内容并生成针对性问题。', uploadLabel: 'PDF 简历', dropTitle: '拖拽文件到这里，或点击选择', dropHint: '仅支持 PDF 文件', target: '目标岗位', targetPlaceholder: '例如：Python 后端开发工程师', uploadAction: '上传并解析', uploading: '上传中...', parsed: '简历解析完成', name: '姓名', education: '学历', skills: '技能', summary: '概述', analysis: '简历分析', resumeScore: '简历综合评分', matched: '匹配技能', missing: '待补充技能', strengths: '优势', weaknesses: '不足', suggestions: '改进建议', difficulty: '面试难度', questionCount: '题目数量', easyOption: '简单 · 基础知识', mediumOption: '中等 · 技术深度', hardOption: '困难 · 系统设计', quick: '3 题 · 快速模式', standard: '5 题 · 标准模式', deep: '8 题 · 深度模式', start: '开始面试', generating: '正在生成问题...', parsingFailed: '简历解析失败，请重试', timeout: '解析超时，请重试', stages: ['正在上传简历...', '正在提取文本...', 'AI 正在解析简历...', 'AI 正在分析内容...', '即将完成...'], parseDone: '解析完成', ready: '面试即将开始', creating: 'AI 正在生成面试问题...', customizing: '正在根据简历定制问题...', startSoon: '即将开始...', prepared: '面试准备完成', tips: ['面试前深呼吸，保持自然和专注', '回答时可以使用 STAR 法则组织内容', '遇到陌生问题，先说明你的分析思路', '项目经验要讲清你的贡献与技术取舍', '简历上的每个技术点都要能展开说明'], startTips: ['深呼吸，保持冷静自信', '回答时尽量结合项目经验', '先理清思路，再组织答案', '不会的问题可以坦诚说明', '注意条理，分点作答'] },
    interview: { preparing: '面试即将开始', preparingHint: 'AI 正在准备面试问题...', interviewer: 'AI 面试官', progress: '第 {current} / {total} 题', exit: '退出', placeholder: '输入你的回答...', evaluating: '评估中...', send: '发送', thinking: 'AI 思考中', finished: '面试已完成', finishedHint: '你的评估报告已经生成。', viewReport: '查看评估报告', tips: ['请做好准备，保持冷静自信', '回答时尽量结合项目经验', '注意条理，分点作答', '面试官会根据你的简历提问'], error: '出现错误：' },
    report: { loading: '正在生成报告...', eyebrow: 'INTERVIEW REPORT', title: '面试评估报告', subtitle: '基于本次回答生成的能力分析与改进建议。', overall: '综合得分', summary: '总体评价', strengths: '优势', weaknesses: '不足', suggestions: '改进建议', questionScores: '各题得分', again: '再来一次', home: '返回记录', failed: '报告加载失败' },
    profile: { eyebrow: 'PROFILE SETTINGS', title: '个人中心', subtitle: '管理个人信息、求职目标与账户安全。', identity: '账户信息', changePhoto: '更换头像', basic: '基本信息', security: '账户安全', firstName: '名', lastName: '姓', gender: '性别', unset: '未设置', male: '男', female: '女', phone: '手机号', university: '学校', careerGoal: '求职目标', location: '所在城市', universityPlaceholder: '学校名称', careerPlaceholder: '例如：AI Agent 开发工程师', locationPlaceholder: '例如：上海', saveProfile: '保存信息', saving: '保存中...', saved: '保存成功', currentPassword: '当前密码', newPassword: '新密码', confirmPassword: '确认新密码', currentPasswordPlaceholder: '输入当前密码', newPasswordPlaceholder: '至少 6 位', confirmPasswordPlaceholder: '再次输入新密码', changePassword: '修改密码', changing: '修改中...', passwordChanged: '密码修改成功', mismatch: '两次密码不一致', minLength: '新密码至少 6 位', avatarFailed: '头像上传失败' },
    footer: { tagline: '清晰练习，认真复盘。', copyright: '© 2026 JianShi AI' },
    demo: { title: '演示模式', titleShort: '演示', hint: '数据由浏览器本地生成，不会调用真实模型接口', reset: '重置演示数据', resetShort: '重置', resetDone: '演示数据已重置', loginHint: '这是在线演示版：已预填演示账号，直接点击登录即可体验「上传简历 → 模拟面试 → 评估报告」完整流程。' },
    apiSettings: { eyebrow: 'AI PROVIDER SETTINGS', title: '个人 API 配置', subtitle: '使用你自己的 API Key。密钥会加密保存，仅用于你的 AI 解析与面试。', required: '开始 AI 功能前，请先添加并验证一个 API 配置。', add: '添加配置', edit: '编辑配置', empty: '还没有 API 配置', emptyHint: '添加一个你有权限使用的模型供应商，然后测试并启用它。', provider: '供应商', identifier: '配置标识', identifierHint: '仅支持小写字母、数字和短横线', name: '显示名称', note: '备注', notePlaceholder: '例如：个人 DeepSeek 账号', website: '官网', protocol: '协议', endpoint: 'API Endpoint', endpointHint: '必须是公开的 HTTPS 地址', apiKey: 'API Key', apiKeyHint: '密钥不会回显，编辑时请重新填写才会更新', models: '模型列表', modelPlaceholder: '输入模型名称后回车', discover: '获取模型', discovering: '获取中...', defaultModel: '默认模型', apiVersion: 'API 版本（可选）', save: '保存配置', saving: '保存中...', test: '测试连接', testing: '测试中...', activate: '启用', active: '当前使用', validated: '已验证', unvalidated: '未验证', remove: '删除配置', deleteConfirm: '确定删除这个 API 配置吗？', saved: '配置已保存，请测试连接后启用。', tested: '连接测试成功', activated: '已启用此配置', deleted: '配置已删除', testBeforeActivate: '请先测试连接', showKey: '显示 Key', hideKey: '隐藏 Key', custom: '自定义', noModels: '请至少填写一个模型', modelRequired: '请选择默认模型' },
  },
  en: {
    common: { brand: 'JianShi', product: 'JianShi AI', records: 'Interviews', upload: 'Upload Resume', apiSettings: 'API settings', profile: 'Profile', logout: 'Sign out', theme: 'Toggle theme', language: 'Switch language', loading: 'Loading...', save: 'Save', cancel: 'Cancel', delete: 'Delete', back: 'Back', score: 'Score', status: 'Status', date: 'Date', actions: 'Actions', completed: 'Completed', inProgress: 'In progress', easy: 'Easy', medium: 'Medium', hard: 'Hard', questions: 'questions', failed: 'Failed to load', retry: 'Retry' },
    auth: { signIn: 'Sign in', signingIn: 'Signing in...', signUp: 'Create account', signingUp: 'Creating account...', welcome: 'Welcome back', createAccount: 'Create your account', subtitle: 'Focused AI interview practice', email: 'Email', password: 'Password', emailPlaceholder: 'Enter your email', passwordPlaceholder: 'Enter your password', firstName: 'First name', lastName: 'Last name', passwordHint: '8+ characters with letters, numbers and symbols', noAccount: 'New to JianShi?', hasAccount: 'Already have an account?', registerNow: 'Create account', signInNow: 'Sign in', registerSuccess: 'Account created. Redirecting...' },
    dashboard: { eyebrow: 'INTERVIEW WORKSPACE', title: 'Interview history', subtitle: 'Track your progress, continue a session, or revisit feedback.', start: 'New interview', emptyTitle: 'No interviews yet', emptyText: 'Upload your resume to begin your first AI interview.', difficulty: 'Difficulty', questionCount: 'Questions', score: 'Score', continue: 'Continue', report: 'View report', deleteConfirm: 'Delete this interview? This cannot be undone.', deleteFailed: 'Delete failed' },
    resume: { eyebrow: 'NEW INTERVIEW', title: 'Upload your resume', subtitle: 'Submit a PDF and JianShi will create a tailored interview from it.', uploadLabel: 'PDF resume', dropTitle: 'Drop your file here, or click to browse', dropHint: 'PDF files only', target: 'Target role', targetPlaceholder: 'e.g. Python Backend Engineer', uploadAction: 'Upload and analyze', uploading: 'Uploading...', parsed: 'Resume analyzed', name: 'Name', education: 'Education', skills: 'Skills', summary: 'Summary', analysis: 'Resume analysis', resumeScore: 'Overall resume score', matched: 'Matched skills', missing: 'Skills to strengthen', strengths: 'Strengths', weaknesses: 'Gaps', suggestions: 'Suggestions', difficulty: 'Interview difficulty', questionCount: 'Number of questions', easyOption: 'Easy · Fundamentals', mediumOption: 'Medium · Technical depth', hardOption: 'Hard · System design', quick: '3 questions · Quick', standard: '5 questions · Standard', deep: '8 questions · Deep dive', start: 'Start interview', generating: 'Generating questions...', parsingFailed: 'Resume analysis failed. Please try again.', timeout: 'Analysis timed out. Please try again.', stages: ['Uploading resume...', 'Extracting text...', 'AI is reading your resume...', 'Analyzing content...', 'Almost ready...'], parseDone: 'Analysis complete', ready: 'Your interview is almost ready', creating: 'AI is creating interview questions...', customizing: 'Tailoring questions to your resume...', startSoon: 'Starting soon...', prepared: 'Interview ready', tips: ['Take a breath and stay focused', 'Use the STAR method to structure examples', 'Explain your reasoning when a topic is unfamiliar', 'Make your contribution and trade-offs clear', 'Be ready to discuss every skill on your resume'], startTips: ['Take a breath and stay confident', 'Connect answers to project experience', 'Organize your thoughts before answering', 'Be honest about what you do not know', 'Use clear, structured points'] },
    interview: { preparing: 'Your interview is about to begin', preparingHint: 'AI is preparing your questions...', interviewer: 'AI Interviewer', progress: 'Question {current} of {total}', exit: 'Exit', placeholder: 'Type your answer...', evaluating: 'Evaluating...', send: 'Send', thinking: 'AI is thinking', finished: 'Interview complete', finishedHint: 'Your evaluation report is ready.', viewReport: 'View evaluation report', tips: ['Get ready and stay confident', 'Connect answers to project experience', 'Keep your answers structured', 'Questions will be based on your resume'], error: 'Something went wrong: ' },
    report: { loading: 'Preparing your report...', eyebrow: 'INTERVIEW REPORT', title: 'Interview evaluation', subtitle: 'A focused review of your answers and next steps.', overall: 'Overall score', summary: 'Summary', strengths: 'Strengths', weaknesses: 'Areas to improve', suggestions: 'Recommendations', questionScores: 'Question scores', again: 'Try another', home: 'Back to interviews', failed: 'Report unavailable' },
    profile: { eyebrow: 'PROFILE SETTINGS', title: 'Profile settings', subtitle: 'Manage your personal details, career goal and account security.', identity: 'Account', changePhoto: 'Change photo', basic: 'Personal information', security: 'Account security', firstName: 'First name', lastName: 'Last name', gender: 'Gender', unset: 'Not set', male: 'Male', female: 'Female', phone: 'Phone', university: 'University', careerGoal: 'Career goal', location: 'Location', universityPlaceholder: 'University name', careerPlaceholder: 'e.g. AI Agent Engineer', locationPlaceholder: 'e.g. Shanghai', saveProfile: 'Save changes', saving: 'Saving...', saved: 'Changes saved', currentPassword: 'Current password', newPassword: 'New password', confirmPassword: 'Confirm password', currentPasswordPlaceholder: 'Enter current password', newPasswordPlaceholder: 'At least 6 characters', confirmPasswordPlaceholder: 'Enter new password again', changePassword: 'Update password', changing: 'Updating...', passwordChanged: 'Password updated', mismatch: 'Passwords do not match', minLength: 'Password must be at least 6 characters', avatarFailed: 'Avatar upload failed' },
    footer: { tagline: 'Practice clearly. Improve deliberately.', copyright: '© 2026 JianShi AI' },
    demo: { title: 'Demo mode', titleShort: 'Demo', hint: 'Data is generated locally in your browser. No real model API is called.', reset: 'Reset demo data', resetShort: 'Reset', resetDone: 'Demo data reset', loginHint: 'This is the online demo: demo credentials are pre-filled. Click sign in to walk through upload → interview → report.' },
    apiSettings: { eyebrow: 'AI PROVIDER SETTINGS', title: 'Personal API settings', subtitle: 'Use your own API key. It is encrypted at rest and used only for your AI sessions.', required: 'Add and verify an API configuration before using AI features.', add: 'Add configuration', edit: 'Edit configuration', empty: 'No API configurations yet', emptyHint: 'Add a model provider you can use, then test and activate it.', provider: 'Provider', identifier: 'Configuration ID', identifierHint: 'Lowercase letters, numbers and hyphens only', name: 'Display name', note: 'Note', notePlaceholder: 'e.g. Personal DeepSeek account', website: 'Website', protocol: 'Protocol', endpoint: 'API endpoint', endpointHint: 'Must be a public HTTPS URL', apiKey: 'API key', apiKeyHint: 'The key is never returned. Re-enter it when editing to change it.', models: 'Models', modelPlaceholder: 'Type a model name and press Enter', discover: 'Fetch models', discovering: 'Fetching...', defaultModel: 'Default model', apiVersion: 'API version (optional)', save: 'Save configuration', saving: 'Saving...', test: 'Test connection', testing: 'Testing...', activate: 'Activate', active: 'Active', validated: 'Verified', unvalidated: 'Not verified', remove: 'Delete configuration', deleteConfirm: 'Delete this API configuration?', saved: 'Saved. Test the connection before activating it.', tested: 'Connection successful', activated: 'Configuration activated', deleted: 'Configuration deleted', testBeforeActivate: 'Test the connection first', showKey: 'Show key', hideKey: 'Hide key', custom: 'Custom', noModels: 'Add at least one model', modelRequired: 'Choose a default model' },
  }
}

const locale = localStorage.getItem('jianshi-locale') || (navigator.language.startsWith('zh') ? 'zh' : 'en')
export default createI18n({ legacy: false, locale, fallbackLocale: 'zh', messages })
