<template>
  <div class="content-wrap"><div class="page-header"><div><p class="eyebrow">{{ t('interviews.eyebrow') }}</p><h1 class="page-title">{{ t('interviews.title') }}</h1><p class="page-subtitle">{{ t('interviews.subtitle') }}</p></div><select v-model="statusFilter" class="status-filter" @change="page = 1; loadInterviews()"><option value="">{{ t('common.allStatus') }}</option><option value="in_progress">{{ t('common.inProgress') }}</option><option value="completed">{{ t('common.completed') }}</option></select></div><section class="card table-shell"><table><thead><tr><th>{{ t('interviews.id') }}</th><th>{{ t('interviews.user') }}</th><th>{{ t('interviews.role') }}</th><th>{{ t('common.difficulty') }}</th><th>{{ t('common.questions') }}</th><th>{{ t('common.score') }}</th><th>{{ t('interviews.status') }}</th><th>{{ t('interviews.time') }}</th><th>{{ t('common.actions') }}</th></tr></thead><tbody><tr v-for="item in interviews" :key="item.id"><td class="muted">{{ item.id }}</td><td>{{ item.user_email }}</td><td class="strong-cell">{{ item.target_position }}</td><td>{{ difficultyLabel(item.difficulty) }}</td><td>{{ item.total_questions }}</td><td><strong v-if="item.overall_score != null" :style="{ color: scoreColor(item.overall_score) }">{{ item.overall_score }}</strong><span v-else class="muted">-</span></td><td><span :class="['badge', item.status === 'completed' ? 'badge-green' : 'badge-yellow']">{{ item.status === 'completed' ? t('common.completed') : t('common.inProgress') }}</span></td><td>{{ formatDate(item.created_at) }}</td><td class="action-cell"><router-link :to="`/interviews/${item.id}`" class="btn-secondary btn-sm">{{ t('common.detail') }}</router-link><button class="btn-danger btn-sm" type="button" @click="handleDelete(item.id)">{{ t('common.delete') }}</button></td></tr><tr v-if="!interviews.length"><td colspan="9" class="table-empty">{{ t('common.noData') }}</td></tr></tbody></table><div class="pagination" v-if="total > perPage"><button class="btn-secondary btn-sm" :disabled="page <= 1" @click="page--; loadInterviews()">{{ t('common.back') }}</button><span>{{ page }} / {{ Math.ceil(total / perPage) }} {{ t('common.page') }}</span><button class="btn-secondary btn-sm" :disabled="page >= Math.ceil(total / perPage)" @click="page++; loadInterviews()">{{ t('common.next') }}</button></div></section></div>
</template>
<script setup>
import { ref } from 'vue'; import { useI18n } from 'vue-i18n'; import { interviewApi } from '../api'
const { t, locale } = useI18n(); const interviews = ref([]); const total = ref(0); const page = ref(1); const perPage = 20; const statusFilter = ref('')
function difficultyLabel(value) { return t(`common.${value}`, value) } function scoreColor(value) { return value >= 7 ? 'var(--success)' : value >= 5 ? 'var(--warning)' : 'var(--danger)' } function formatDate(value) { if (!value) return ''; return new Date(value).toLocaleString(locale.value === 'zh' ? 'zh-CN' : 'en-US', { dateStyle:'medium', timeStyle:'short' }) }
async function loadInterviews() { try { const data = await interviewApi.list({ page: page.value, per_page: perPage, status: statusFilter.value || undefined }); interviews.value = data.items || []; total.value = data.total || 0 } catch (e) { console.error(e) } }
async function handleDelete(id) { if (!confirm(t('common.confirmDelete'))) return; try { await interviewApi.delete(id); await loadInterviews() } catch (e) { alert(`${t('common.deleteFailed')}: ${e.message}`) } }
loadInterviews()
</script>
<style scoped>
.status-filter { width:150px; } .muted { color:var(--text-faint); } .strong-cell { color:var(--text); font-weight:600; } .action-cell { display:flex; align-items:center; gap:6px; } .table-empty { padding:42px; color:var(--text-faint); text-align:center; }
@media(max-width:620px) { .status-filter { width:100%; } }
</style>
