<template>
  <div class="content-wrap"><div class="detail-heading"><router-link to="/interviews" class="back-link"><ArrowLeft :size="15" />{{ t('common.back') }}</router-link><div><p class="eyebrow">{{ t('detail.eyebrow') }}</p><h1 class="page-title">{{ t('detail.title') }} #{{ interviewId }}</h1></div></div><div v-if="loading" class="card loading-state"><LoaderCircle class="spin" :size="22" /><span>{{ t('common.loading') }}</span></div><template v-else-if="detail"><section class="card info-card"><div><span>{{ t('detail.role') }}</span><strong>{{ detail.target_position }}</strong></div><div><span>{{ t('detail.difficulty') }}</span><strong>{{ difficultyLabel(detail.difficulty) }}</strong></div><div><span>{{ t('detail.questions') }}</span><strong>{{ detail.total_questions }}</strong></div><div><span>{{ t('detail.overall') }}</span><strong :style="{ color: detail.overall_score != null ? scoreColor(detail.overall_score) : 'var(--text-faint)' }">{{ detail.overall_score ?? '-' }}</strong></div><div><span>{{ t('detail.status') }}</span><span :class="['badge', detail.status === 'completed' ? 'badge-green' : 'badge-yellow']">{{ detail.status === 'completed' ? t('common.completed') : t('common.inProgress') }}</span></div></section><section class="card report-card" v-if="detail.report?.summary"><div class="section-heading"><FileText :size="18" /><h2>{{ t('detail.report') }}</h2></div><p class="long-copy">{{ detail.report.summary }}</p><div class="report-cols"><div v-if="detail.report.strengths?.length"><h3>{{ t('detail.strengths') }}</h3><ul><li v-for="(item,index) in detail.report.strengths" :key="index">{{ item }}</li></ul></div><div v-if="detail.report.weaknesses?.length"><h3>{{ t('detail.weaknesses') }}</h3><ul><li v-for="(item,index) in detail.report.weaknesses" :key="index">{{ item }}</li></ul></div></div></section><section class="card report-card"><div class="section-heading"><MessagesSquare :size="18" /><h2>{{ t('detail.conversation') }}</h2></div><div v-for="message in detail.messages" :key="message.id" :class="['message-row', message.role]"><div class="message-meta"><span class="message-avatar"><Sparkles v-if="message.role === 'interviewer'" :size="14" /><UserRound v-else :size="14" /></span><strong>{{ message.role === 'interviewer' ? t('detail.interviewer') : t('detail.candidate') }}</strong></div><p>{{ message.content }}</p><span v-if="message.score != null" class="message-score">{{ t('detail.rating') }} {{ message.score }}/10<span v-if="message.feedback"> · {{ message.feedback }}</span></span></div></section></template></div>
</template>
<script setup>
import { ref } from 'vue'; import { useI18n } from 'vue-i18n'; import { useRoute } from 'vue-router'; import { ArrowLeft, FileText, LoaderCircle, MessagesSquare, Sparkles, UserRound } from '@lucide/vue'; import { interviewApi } from '../api'
const { t } = useI18n(); const route = useRoute(); const interviewId = route.params.id; const detail = ref(null); const loading = ref(true)
function difficultyLabel(value) { return t(`common.${value}`, value) } function scoreColor(value) { return value >= 7 ? 'var(--success)' : value >= 5 ? 'var(--warning)' : 'var(--danger)' }
interviewApi.detail(interviewId).then(data => { detail.value = data }).catch(e => console.error(e)).finally(() => { loading.value = false })
</script>
<style scoped>
.detail-heading { display:flex; align-items:flex-start; gap:18px; margin-bottom:28px; } .back-link { display:inline-flex; align-items:center; gap:6px; padding-top:6px; color:var(--text-soft); font-size:12px; } .back-link:hover { color:var(--text); } .detail-heading .page-title { margin-top:8px; }
.info-card { display:grid; grid-template-columns:repeat(5,1fr); gap:18px; } .info-card > div { display:flex; flex-direction:column; gap:8px; } .info-card > div > span:first-child { color:var(--text-faint); font-size:11px; } .info-card strong { color:var(--text); font-size:14px; font-weight:650; } .report-card { margin-top:16px; } .section-heading { display:flex; align-items:center; gap:10px; margin-bottom:16px; } .section-heading svg { color:var(--text-soft); } .section-heading h2 { font-size:17px; font-weight:650; } .long-copy,.report-cols li,.message-row p { color:var(--text-soft); font-size:13px; line-height:1.8; } .report-cols { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-top:22px; } .report-cols h3 { margin-bottom:8px; color:var(--text-soft); font-size:12px; } .report-cols ul { padding-left:16px; }
.message-row { margin-top:16px; padding:17px; border:1px solid var(--border); border-radius:var(--radius-md); background:var(--bg-soft); } .message-row.candidate { background:var(--bg-hover); } .message-meta { display:flex; align-items:center; gap:8px; margin-bottom:9px; color:var(--text-soft); font-size:11px; } .message-avatar { width:26px; height:26px; display:grid; place-items:center; border:1px solid var(--border); border-radius:50%; color:var(--text-soft); background:var(--bg-elevated); } .message-score { display:block; margin-top:9px; color:var(--text-faint); font-size:11px; }
.spin { animation:spin 1s linear infinite; } @keyframes spin { to { transform:rotate(360deg); } }
@media(max-width:820px) { .info-card { grid-template-columns:repeat(3,1fr); } } @media(max-width:560px) { .detail-heading { gap:10px; } .info-card { grid-template-columns:1fr 1fr; } .report-cols { grid-template-columns:1fr; } }
</style>
