<template>
  <div class="auth-page"><div class="auth-toolbar"><PreferenceControls /></div><div class="auth-layout"><section class="auth-intro"><div class="auth-brand"><span class="brand-mark"><Sparkles :size="17" /></span><span>{{ t('common.brand') }}</span></div><p class="eyebrow">{{ t('auth.eyebrow') }}</p><h1>{{ t('auth.title') }}</h1><p>{{ t('auth.subtitle') }}</p><div class="intro-rule"></div></section><section class="auth-card card"><p class="eyebrow">{{ t('common.product') }}</p><h2>{{ t('common.login') }}</h2><form @submit.prevent="handleLogin"><div class="form-group"><label>{{ t('common.email') }}</label><input v-model="email" type="email" :placeholder="t('auth.placeholderEmail')" required /></div><div class="form-group"><label>{{ t('common.password') }}</label><input v-model="password" type="password" :placeholder="t('auth.placeholderPassword')" required /></div><p v-if="error" class="error form-message">{{ error }}</p><button class="btn-primary auth-submit" type="submit" :disabled="loading">{{ loading ? t('common.loggingIn') : t('common.login') }}<ArrowUpRight :size="16" /></button></form></section></div></div>
</template>
<script setup>
import { ref } from 'vue'; import { useI18n } from 'vue-i18n'; import { useRouter } from 'vue-router'; import { ArrowUpRight, Sparkles } from '@lucide/vue'; import { useAuthStore } from '../stores/auth'; import { authApi } from '../api'; import PreferenceControls from '../components/PreferenceControls.vue'
const { t } = useI18n(); const router = useRouter(); const authStore = useAuthStore(); const email = ref('admin@jianshi-ai.local'); const password = ref(''); const error = ref(''); const loading = ref(false)
async function handleLogin() { error.value = ''; loading.value = true; try { const data = await authApi.login(email.value, password.value); authStore.setAuth({ ...data, email: email.value }); router.push('/') } catch (e) { error.value = e.message } finally { loading.value = false } }
</script>
<style scoped>
.auth-page { min-height:100vh; padding:28px 40px; display:grid; place-items:center; } .auth-toolbar { position:fixed; top:24px; right:40px; } .auth-layout { width:min(100%,850px); display:grid; grid-template-columns:1fr 390px; gap:76px; align-items:center; } .auth-intro { padding:24px 0; } .auth-brand { display:inline-flex; align-items:center; gap:10px; margin-bottom:74px; font-size:18px; font-weight:750; } .brand-mark { width:32px; height:32px; display:grid; place-items:center; border-radius:9px; color:var(--primary-text); background:var(--primary); } .auth-intro h1 { margin-top:17px; font-size:clamp(38px,6vw,58px); font-weight:650; } .auth-intro > p:not(.eyebrow) { max-width:300px; margin-top:20px; color:var(--text-soft); line-height:1.7; } .intro-rule { width:80px; height:1px; margin-top:78px; background:var(--border-strong); } .auth-card { padding:34px; } .auth-card h2 { margin:8px 0 28px; font-size:26px; font-weight:650; } .auth-submit { width:100%; margin-top:4px; } .form-message { margin:-4px 0 14px; }
@media(max-width:720px) { .auth-page { padding:84px 16px 28px; } .auth-toolbar { top:20px; right:16px; } .auth-layout { display:block; } .auth-intro { padding:0 8px 28px; } .auth-brand { margin-bottom:42px; } .auth-intro h1 { font-size:42px; } .intro-rule { margin-top:32px; } .auth-card { padding:24px 20px; } }
</style>
