<template>
  <div class="content-wrap"><div class="page-header"><div><p class="eyebrow">{{ t('users.eyebrow') }}</p><h1 class="page-title">{{ t('users.title') }}</h1><p class="page-subtitle">{{ t('users.subtitle') }}</p></div><div class="search-box"><Search :size="16" /><input v-model="keyword" :placeholder="t('common.search')" @input="debouncedSearch" /></div></div><section class="card table-shell"><table><thead><tr><th>{{ t('users.id') }}</th><th>{{ t('users.email') }}</th><th>{{ t('users.name') }}</th><th>{{ t('users.status') }}</th><th>{{ t('users.created') }}</th><th>{{ t('common.actions') }}</th></tr></thead><tbody><tr v-for="user in users" :key="user.id"><td class="muted">{{ user.id }}</td><td class="strong-cell">{{ user.email }}</td><td>{{ user.first_name }} {{ user.last_name }}</td><td><span :class="['badge', user.is_active ? 'badge-green' : 'badge-red']">{{ user.is_active ? t('common.enabled') : t('common.disabled') }}</span></td><td>{{ formatDate(user.created_at) }}</td><td><button :class="user.is_active ? 'btn-danger btn-sm' : 'btn-primary btn-sm'" type="button" @click="toggleActive(user)">{{ user.is_active ? t('common.disable') : t('common.enable') }}</button></td></tr><tr v-if="!users.length"><td colspan="6" class="table-empty">{{ t('common.noData') }}</td></tr></tbody></table><div class="pagination" v-if="total > perPage"><button class="btn-secondary btn-sm" :disabled="page <= 1" @click="page--; loadUsers()">{{ t('common.back') }}</button><span>{{ page }} / {{ Math.ceil(total / perPage) }} {{ t('common.page') }}</span><button class="btn-secondary btn-sm" :disabled="page >= Math.ceil(total / perPage)" @click="page++; loadUsers()">{{ t('common.next') }}</button></div></section></div>
</template>
<script setup>
import { ref } from 'vue'; import { useI18n } from 'vue-i18n'; import { Search } from '@lucide/vue'; import { userApi } from '../api'
const { t, locale } = useI18n(); const users = ref([]); const total = ref(0); const page = ref(1); const perPage = 20; const keyword = ref(''); let searchTimer = null
function formatDate(value) { if (!value) return ''; return new Date(value).toLocaleString(locale.value === 'zh' ? 'zh-CN' : 'en-US', { dateStyle: 'medium' }) }
async function loadUsers() { try { const data = await userApi.list({ page: page.value, per_page: perPage, keyword: keyword.value || undefined }); users.value = data.items || []; total.value = data.total || 0 } catch (e) { console.error(e) } }
function debouncedSearch() { clearTimeout(searchTimer); searchTimer = setTimeout(() => { page.value = 1; loadUsers() }, 300) }
async function toggleActive(user) { try { const data = await userApi.toggleActive(user.id); user.is_active = data.is_active } catch (e) { console.error(e) } }
loadUsers()
</script>
<style scoped>
.search-box { width:260px; display:flex; align-items:center; gap:8px; padding:0 12px; border:1px solid var(--border); border-radius:var(--radius-md); background:var(--bg-soft); } .search-box svg { flex:0 0 auto; color:var(--text-faint); } .search-box input { min-height:40px; padding:0; border:0; background:transparent; box-shadow:none; } .search-box input:focus { box-shadow:none; } .muted { color:var(--text-faint); } .strong-cell { color:var(--text); font-weight:600; } .table-empty { padding:42px; color:var(--text-faint); text-align:center; }
@media(max-width:620px) { .search-box { width:100%; } }
</style>
