<template>
  <div class="interview-page">
    <div v-if="preparing" class="prepare-overlay"><div class="prepare-card glass-panel"><div class="prepare-icon"><Sparkles :size="28" /></div><p class="eyebrow">{{ t('common.product') }}</p><h2>{{ t('interview.preparing') }}</h2><p>{{ prepareTip }}</p><div class="prepare-progress"><div class="prepare-bar" :style="{ width: `${preparePercent}%` }"></div></div><span>{{ t('interview.preparingHint') }}</span></div></div>
    <header v-if="!preparing" class="interview-header"><div class="interviewer-label"><span class="ai-avatar"><Sparkles :size="15" /></span><span>{{ t('interview.interviewer') }}</span></div><span class="progress">{{ t('interview.progress', { current: currentIndex + 1, total: totalQuestions }) }}</span><router-link to="/dashboard" class="icon-button" :title="t('interview.exit')" :aria-label="t('interview.exit')"><X :size="17" /></router-link></header>
    <main v-if="!preparing" ref="chatArea" class="chat-area">
      <div v-for="(msg, index) in messages" :key="index" :class="['message', msg.role]"><div v-if="msg.role === 'interviewer'" class="avatar-col"><span class="ai-avatar"><Sparkles :size="15" /></span></div><div class="bubble"><div class="bubble-content" v-html="renderContent(msg.content)"></div><div v-if="msg.score != null" class="bubble-score">{{ t('common.score') }} {{ msg.score }}/10</div></div><div v-if="msg.role === 'candidate'" class="avatar-col"><img v-if="userAvatar && !avatarError" :src="userAvatar" alt="" class="user-avatar" @error="avatarError = true" /><span v-else class="user-avatar-placeholder">{{ userInitial }}</span></div></div>
      <div v-if="streamingText" class="message interviewer"><div class="avatar-col"><span class="ai-avatar thinking"><Sparkles :size="15" /></span></div><div class="bubble"><div class="bubble-content" v-html="renderContent(streamingText)"></div><span class="cursor-blink">|</span></div></div>
      <div v-if="thinking && !streamingText" class="message interviewer"><div class="avatar-col"><span class="ai-avatar thinking"><Sparkles :size="15" /></span></div><div class="bubble thinking-bubble">{{ t('interview.thinking') }}<span class="dots">...</span></div></div>
    </main>
    <form v-if="!preparing && !finished" class="input-area" @submit.prevent="handleSubmit"><textarea v-model="answer" :placeholder="t('interview.placeholder')" :disabled="thinking" rows="3" @keydown.enter.exact.prevent="handleSubmit"></textarea><button class="btn-primary" type="submit" :disabled="!answer.trim() || thinking">{{ thinking ? t('interview.evaluating') : t('interview.send') }}<ArrowUpRight :size="16" /></button></form>
    <div v-if="!preparing && finished" class="finish-area"><div><p class="eyebrow">{{ t('interview.finished') }}</p><h2>{{ t('interview.finishedHint') }}</h2></div><router-link :to="`/interview/${interviewId}/report`" class="btn-primary">{{ t('interview.viewReport') }}<ArrowUpRight :size="16" /></router-link></div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute } from 'vue-router'
import { ArrowUpRight, Sparkles, X } from '@lucide/vue'
import { useAuthStore } from '../stores/auth'
import { submitAnswerStream, getMessages } from '../api/interview'
const { t, tm } = useI18n(); const route = useRoute(); const authStore = useAuthStore(); const interviewId = route.params.id
const messages = ref([]); const answer = ref(''); const thinking = ref(false); const finished = ref(false); const currentIndex = ref(0); const totalQuestions = ref(5); const chatArea = ref(null); const streamingText = ref(''); const preparing = ref(true); const preparePercent = ref(0); const prepareTip = ref(''); const avatarError = ref(false)
const userAvatar = computed(() => authStore.userAvatar || ''); const userInitial = computed(() => (authStore.userName || 'JS').charAt(0).toUpperCase())
function renderContent(text) { if (!text) return ''; const cleaned = text.replace(/```json\s*\{[\s\S]*?\}\s*```/g, '').replace(/\{[^{}]*"score"\s*:\s*[\d.]+[^{}]*\}/g, '').trim(); return cleaned.replace(/\n/g, '<br>') }
function scrollToBottom() { nextTick(() => { if (chatArea.value) chatArea.value.scrollTop = chatArea.value.scrollHeight }) }
onMounted(async () => { const tips = tm('interview.tips'); let tipIndex = 0; prepareTip.value = tips[0]; const tipTimer = setInterval(() => { tipIndex = (tipIndex + 1) % tips.length; prepareTip.value = tips[tipIndex] }, 1500); const barTimer = setInterval(() => { if (preparePercent.value < 90) preparePercent.value += 2 }, 100); try { const data = await getMessages(interviewId); const list = Array.isArray(data) ? data : (data.items || data); messages.value = list.map(item => ({ role: item.role, content: item.content, score: item.score, feedback: item.feedback })); const indices = list.map(item => item.question_index).filter(index => index != null); if (indices.length) currentIndex.value = Math.max(...indices) } catch (e) { console.error('Failed to load messages:', e) } preparePercent.value = 100; clearInterval(barTimer); clearInterval(tipTimer); setTimeout(() => { preparing.value = false }, 600); nextTick(scrollToBottom) })
async function handleSubmit() { if (!answer.value.trim() || thinking.value) return; const myAnswer = answer.value.trim(); answer.value = ''; messages.value.push({ role: 'candidate', content: myAnswer }); scrollToBottom(); thinking.value = true; streamingText.value = ''; let rawStreamText = ''; try { await submitAnswerStream(interviewId, myAnswer, chunk => { rawStreamText += chunk; let display = rawStreamText.replace(/```json\s*\{[\s\S]*?\}\s*```/g, '').replace(/\{[^{}]*"score"\s*:\s*[\d.]+[^{}]*\}/g, ''); display = display.replace(/```json[\s\S]*$/g, '').replace(/\{[^}]*$/g, match => /["']?score/.test(match) || /^\{\s*$/.test(match) ? '' : match); streamingText.value = display.trim(); scrollToBottom() }, data => { if (rawStreamText.trim()) { const displayText = rawStreamText.replace(/```json\s*\{[\s\S]*?\}\s*```/g, '').replace(/\{[^{}]*"score"\s*:\s*[\d.]+[^{}]*\}/g, '').trim(); if (displayText) messages.value.push({ role: 'interviewer', content: displayText, score: data.score }) } streamingText.value = ''; rawStreamText = ''; const lastCandidate = [...messages.value].reverse().find(message => message.role === 'candidate'); if (lastCandidate) lastCandidate.score = data.score; if (data.is_finished) finished.value = true; else if (data.next_question) { currentIndex.value = data.question_index + 1; messages.value.push({ role: 'interviewer', content: data.next_question }) } scrollToBottom() }) } catch (e) { streamingText.value = ''; messages.value.push({ role: 'interviewer', content: t('interview.error') + e.message }); scrollToBottom() } finally { thinking.value = false } }
</script>

<style scoped>
.interview-page { min-height: calc(100vh - 72px); display: flex; flex-direction: column; background: var(--bg); } .prepare-overlay { position: fixed; inset: 0; z-index: 30; display: grid; place-items: center; padding: 20px; background: var(--bg); } .prepare-card { width: min(100%, 460px); padding: 52px 36px; text-align: center; } .prepare-icon { width: 62px; height: 62px; margin: 0 auto 22px; display: grid; place-items: center; border: 1px solid var(--border); border-radius: 50%; background: var(--bg-soft); animation: pulse 1.8s ease-in-out infinite; } .prepare-card h2 { margin-top: 12px; font-size: 23px; font-weight: 650; } .prepare-card p:not(.eyebrow) { margin-top: 10px; color: var(--text-soft); font-size: 14px; } .prepare-progress { height: 5px; margin: 28px auto 10px; overflow: hidden; border-radius: 99px; background: var(--bg-hover); } .prepare-bar { height: 100%; background: var(--primary); transition: width .3s ease; } .prepare-card > span { color: var(--text-faint); font-size: 11px; }
.interview-header { width: min(100%, 820px); min-height: 68px; margin: 0 auto; padding: 0 20px; display: flex; align-items: center; justify-content: space-between; gap: 18px; } .interviewer-label { display: flex; align-items: center; gap: 9px; font-size: 13px; font-weight: 650; } .progress { color: var(--text-faint); font-size: 12px; } .ai-avatar { width: 34px; height: 34px; flex: 0 0 auto; display: grid; place-items: center; border: 1px solid var(--border); border-radius: 50%; color: var(--text); background: var(--bg-elevated); } .ai-avatar.thinking { animation: pulse 1.2s ease-in-out infinite; }
.chat-area { width: min(100%, 820px); flex: 1; margin: 0 auto; padding: 24px 20px 34px; overflow-y: auto; display: flex; flex-direction: column; gap: 18px; } .message { display: flex; align-items: flex-start; gap: 10px; } .message.candidate { justify-content: flex-end; } .avatar-col { flex: 0 0 auto; margin-top: 2px; } .user-avatar, .user-avatar-placeholder { width: 34px; height: 34px; border-radius: 50%; object-fit: cover; border: 1px solid var(--border); } .user-avatar-placeholder { display: grid; place-items: center; color: var(--primary-text); background: var(--primary); font-size: 12px; font-weight: 700; }
.bubble { max-width: min(72%, 560px); padding: 14px 16px; color: var(--text); border: 1px solid var(--border); border-radius: 14px; background: var(--bg-elevated); box-shadow: 0 8px 28px rgba(0, 0, 0, .04); font-size: 14px; line-height: 1.75; } .candidate .bubble { color: var(--primary-text); background: var(--primary); border-color: var(--primary); } .bubble-content { overflow-wrap: anywhere; } .bubble-score { margin-top: 9px; padding-top: 8px; border-top: 1px solid var(--border); color: var(--text-soft); font-size: 11px; } .candidate .bubble-score { color: rgba(255, 255, 255, .7); border-color: rgba(255, 255, 255, .18); } .thinking-bubble { color: var(--text-soft); font-style: italic; } .dots { margin-left: 2px; animation: blink 1s steps(2, end) infinite; } .cursor-blink { color: var(--text-soft); animation: blink .8s step-end infinite; }
.input-area, .finish-area { width: min(100%, 820px); margin: 0 auto; padding: 16px 20px 24px; display: flex; align-items: flex-end; gap: 12px; } .input-area { border-top: 1px solid var(--border); } .input-area textarea { min-height: 72px; resize: none; } .input-area button { min-width: 96px; } .finish-area { align-items: center; justify-content: space-between; border-top: 1px solid var(--border); } .finish-area h2 { margin-top: 7px; font-size: 17px; font-weight: 600; }
@keyframes pulse { 0%, 100% { transform: scale(1); opacity: 1; } 50% { transform: scale(1.06); opacity: .65; } } @keyframes blink { 50% { opacity: 0; } }
@media (max-width: 640px) { .interview-page { min-height: calc(100vh - 64px); } .interview-header { min-height: 60px; padding: 0 16px; } .chat-area { padding: 18px 16px 28px; } .bubble { max-width: 84%; } .input-area, .finish-area { padding: 12px 16px 18px; } .input-area { flex-direction: column; align-items: stretch; } .input-area button { width: 100%; } .finish-area { align-items: stretch; flex-direction: column; } .finish-area .btn-primary { width: 100%; } }
</style>
