<template>
  <div class="container content-narrow">
    <div class="page-header"><div><p class="eyebrow">{{ t('profile.eyebrow') }}</p><h1 class="page-title">{{ t('profile.title') }}</h1><p class="page-subtitle">{{ t('profile.subtitle') }}</p></div></div>
    <section class="card identity-card"><div class="avatar-wrapper" @click="$refs.avatarInput.click()"><img v-if="profile.avatar" :src="avatarUrl" alt="" class="avatar-img" /><span v-else class="avatar-placeholder">{{ initials }}</span><span class="avatar-overlay"><ImagePlus :size="18" /></span><input ref="avatarInput" type="file" accept="image/*" hidden @change="handleAvatarChange" /></div><div><p class="eyebrow">{{ t('profile.identity') }}</p><h2>{{ profile.first_name || '' }} {{ profile.last_name || '' }}</h2><p>{{ profile.email }}</p></div><span class="identity-action">{{ t('profile.changePhoto') }}</span></section>
    <section class="card profile-card"><div class="section-heading"><UserRound :size="19" /><div><h2>{{ t('profile.basic') }}</h2><p>{{ t('profile.subtitle') }}</p></div></div><div class="form-row"><div class="form-group"><label>{{ t('profile.lastName') }}</label><input v-model="form.last_name" :placeholder="t('profile.lastName')" /></div><div class="form-group"><label>{{ t('profile.firstName') }}</label><input v-model="form.first_name" :placeholder="t('profile.firstName')" /></div></div><div class="form-row"><div class="form-group"><label>{{ t('profile.gender') }}</label><select v-model="form.gender"><option value="">{{ t('profile.unset') }}</option><option value="male">{{ t('profile.male') }}</option><option value="female">{{ t('profile.female') }}</option></select></div><div class="form-group"><label>{{ t('profile.phone') }}</label><input v-model="form.phone" :placeholder="t('profile.phone')" /></div></div><div class="form-group"><label>{{ t('profile.university') }}</label><input v-model="form.university" :placeholder="t('profile.universityPlaceholder')" /></div><div class="form-group"><label>{{ t('profile.careerGoal') }}</label><input v-model="form.career_goal" :placeholder="t('profile.careerPlaceholder')" /></div><div class="form-group"><label>{{ t('profile.location') }}</label><input v-model="form.location" :placeholder="t('profile.locationPlaceholder')" /></div><p v-if="profileMsg" :class="profileOk ? 'success-msg' : 'error'">{{ profileMsg }}</p><div class="form-actions"><button class="btn-primary" type="button" @click="handleSaveProfile" :disabled="saving">{{ saving ? t('profile.saving') : t('profile.saveProfile') }}<Check :size="16" /></button></div></section>
    <section class="card profile-card"><div class="section-heading"><LockKeyhole :size="19" /><div><h2>{{ t('profile.security') }}</h2><p>{{ t('profile.subtitle') }}</p></div></div><div class="form-group"><label>{{ t('profile.currentPassword') }}</label><input v-model="pwForm.old_password" type="password" :placeholder="t('profile.currentPasswordPlaceholder')" /></div><div class="form-group"><label>{{ t('profile.newPassword') }}</label><input v-model="pwForm.new_password" type="password" :placeholder="t('profile.newPasswordPlaceholder')" /></div><div class="form-group"><label>{{ t('profile.confirmPassword') }}</label><input v-model="pwForm.confirm_password" type="password" :placeholder="t('profile.confirmPasswordPlaceholder')" /></div><p v-if="pwMsg" :class="pwOk ? 'success-msg' : 'error'">{{ pwMsg }}</p><div class="form-actions"><button class="btn-secondary" type="button" @click="handleChangePassword" :disabled="changingPw">{{ changingPw ? t('profile.changing') : t('profile.changePassword') }}<ArrowUpRight :size="16" /></button></div></section>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { ArrowUpRight, Check, ImagePlus, LockKeyhole, UserRound } from '@lucide/vue'
import { getProfile, updateProfile, uploadAvatar, changePassword } from '../api/user'
const { t } = useI18n(); const profile = ref({}); const form = ref({ first_name: '', last_name: '', gender: '', phone: '', university: '', career_goal: '', location: '' }); const pwForm = ref({ old_password: '', new_password: '', confirm_password: '' }); const saving = ref(false); const changingPw = ref(false); const profileMsg = ref(''); const profileOk = ref(false); const pwMsg = ref(''); const pwOk = ref(false)
const avatarUrl = computed(() => profile.value.avatar || ''); const initials = computed(() => `${profile.value.last_name || ''}${profile.value.first_name || ''}`.slice(0, 2).toUpperCase() || 'JS')
onMounted(async () => { try { const data = await getProfile(); profile.value = data; form.value = { first_name: data.first_name || '', last_name: data.last_name || '', gender: data.gender || '', phone: data.phone || '', university: data.university || '', career_goal: data.career_goal || '', location: data.location || '' } } catch (e) { console.error(e) } })
async function handleAvatarChange(e) { const avatarFile = e.target.files[0]; if (!avatarFile) return; try { const data = await uploadAvatar(avatarFile); profile.value.avatar = data.avatar } catch (e) { alert(`${t('profile.avatarFailed')}: ${e.message}`) } }
async function handleSaveProfile() { profileMsg.value = ''; profileOk.value = false; saving.value = true; try { await updateProfile(form.value); profile.value = { ...profile.value, ...form.value }; profileMsg.value = t('profile.saved'); profileOk.value = true } catch (e) { profileMsg.value = e.message } finally { saving.value = false } }
async function handleChangePassword() { pwMsg.value = ''; pwOk.value = false; if (pwForm.value.new_password !== pwForm.value.confirm_password) { pwMsg.value = t('profile.mismatch'); return } if (pwForm.value.new_password.length < 6) { pwMsg.value = t('profile.minLength'); return } changingPw.value = true; try { await changePassword(pwForm.value.old_password, pwForm.value.new_password); pwMsg.value = t('profile.passwordChanged'); pwOk.value = true; pwForm.value = { old_password: '', new_password: '', confirm_password: '' } } catch (e) { pwMsg.value = e.message } finally { changingPw.value = false } }
</script>

<style scoped>
.identity-card { display: flex; align-items: center; gap: 18px; margin-bottom: 16px; } .avatar-wrapper { width: 72px; height: 72px; position: relative; flex: 0 0 auto; overflow: hidden; border-radius: 50%; cursor: pointer; border: 1px solid var(--border); } .avatar-img, .avatar-placeholder { width: 100%; height: 100%; object-fit: cover; } .avatar-placeholder { display: grid; place-items: center; color: var(--primary-text); background: var(--primary); font-size: 19px; font-weight: 700; } .avatar-overlay { position: absolute; inset: 0; display: grid; place-items: center; color: white; background: rgba(0, 0, 0, .54); opacity: 0; transition: .2s ease; } .avatar-wrapper:hover .avatar-overlay { opacity: 1; } .identity-card h2 { margin-top: 6px; font-size: 18px; font-weight: 650; } .identity-card p:last-of-type { margin-top: 4px; color: var(--text-soft); font-size: 13px; } .identity-action { margin-left: auto; color: var(--text-faint); font-size: 11px; }
.profile-card { margin-top: 16px; } .section-heading { display: flex; align-items: flex-start; gap: 12px; margin-bottom: 28px; } .section-heading > svg { color: var(--text-soft); margin-top: 2px; } .section-heading h2 { font-size: 18px; font-weight: 650; } .section-heading p { margin-top: 6px; color: var(--text-soft); font-size: 13px; } .form-actions { display: flex; justify-content: flex-end; margin-top: 6px; }
@media (max-width: 520px) { .identity-card { align-items: flex-start; flex-wrap: wrap; } .identity-action { width: 100%; margin-left: 90px; margin-top: -12px; } .form-actions .btn-primary, .form-actions .btn-secondary { width: 100%; } }
</style>
