<template>
  <div class="container content-narrow">
    <div class="page-header"><div><p class="eyebrow">{{ t('resume.eyebrow') }}</p><h1 class="page-title">{{ t('resume.title') }}</h1><p class="page-subtitle">{{ t('resume.subtitle') }}</p></div></div>
    <section class="card workflow-card">
      <div v-if="step === 1">
        <div class="step-heading"><span class="step-number">01</span><div><h2>{{ t('resume.uploadLabel') }}</h2><p>{{ t('resume.dropHint') }}</p></div></div>
        <div class="upload-area" @click="$refs.fileInput.click()" @dragover.prevent @drop.prevent="onDrop"><input ref="fileInput" type="file" accept=".pdf" hidden @change="onFileChange" /><FileUp :size="26" /><strong v-if="!file">{{ t('resume.dropTitle') }}</strong><strong v-else>{{ file.name }}</strong><span v-if="!file">{{ t('resume.dropHint') }}</span><span v-else>{{ formatSize(file.size) }}</span></div>
        <div class="form-group"><label>{{ t('resume.target') }}</label><input v-model="targetPosition" :placeholder="t('resume.targetPlaceholder')" /></div>
        <p v-if="error" class="error form-message">{{ error }}</p><button class="btn-primary full-width" type="button" @click="handleUpload" :disabled="!file || uploading">{{ uploading ? t('resume.uploading') : t('resume.uploadAction') }}<ArrowUpRight :size="16" /></button>
      </div>

      <div v-else-if="step === 'parsing'" class="progress-stage"><div class="stage-icon"><FileSearch :size="28" /></div><p class="eyebrow">02 / 03</p><h2>{{ parsingTitle }}</h2><div class="progress-track"><div class="progress-fill" :style="{ width: progress + '%' }"></div></div><div class="progress-meta"><span>{{ progress }}%</span><span>{{ currentTip }}</span></div></div>

      <div v-else-if="step === 2">
        <div class="step-heading"><span class="step-number">02</span><div><h2>{{ t('resume.parsed') }}</h2><p>{{ t('resume.analysis') }}</p></div><CheckCircle2 class="step-check" :size="22" /></div>
        <div class="parsed-grid" v-if="parsedContent"><div v-if="parsedContent.name"><span>{{ t('resume.name') }}</span><strong>{{ parsedContent.name }}</strong></div><div v-if="parsedContent.education"><span>{{ t('resume.education') }}</span><strong>{{ parsedContent.education }}</strong></div><div v-if="parsedContent.skills?.length" class="wide"><span>{{ t('resume.skills') }}</span><div class="tag-list"><span v-for="skill in parsedContent.skills" :key="skill" class="tag">{{ skill }}</span></div></div><div v-if="parsedContent.summary" class="wide"><span>{{ t('resume.summary') }}</span><p>{{ parsedContent.summary }}</p></div></div>
        <div v-if="analysis" class="analysis-panel"><div class="analysis-header"><div><p class="eyebrow">{{ t('resume.analysis') }}</p><h3>{{ t('resume.resumeScore') }}</h3></div><div v-if="analysis.overall_score" class="score-badge" :style="{ color: scoreColor(analysis.overall_score) }">{{ analysis.overall_score }}</div></div><p v-if="analysis.summary" class="analysis-summary">{{ analysis.summary }}</p><div class="analysis-columns"><div v-if="analysis.keyword_match?.length"><h4>{{ t('resume.matched') }}</h4><div class="tag-list"><span v-for="k in analysis.keyword_match" :key="k" class="tag tag-green">{{ k }}</span></div></div><div v-if="analysis.missing_keywords?.length"><h4>{{ t('resume.missing') }}</h4><div class="tag-list"><span v-for="k in analysis.missing_keywords" :key="k" class="tag tag-red">{{ k }}</span></div></div></div><div class="analysis-columns"><div v-if="analysis.strengths?.length"><h4 class="success-text">{{ t('resume.strengths') }}</h4><ul><li v-for="(s, i) in analysis.strengths" :key="i">{{ s }}</li></ul></div><div v-if="analysis.weaknesses?.length"><h4 class="danger-text">{{ t('resume.weaknesses') }}</h4><ul><li v-for="(w, i) in analysis.weaknesses" :key="i">{{ w }}</li></ul></div></div><div v-if="analysis.suggestions?.length"><h4>{{ t('resume.suggestions') }}</h4><ul><li v-for="(s, i) in analysis.suggestions" :key="i">{{ s }}</li></ul></div></div>
        <div class="config-grid"><div class="form-group"><label>{{ t('resume.difficulty') }}</label><select v-model="difficulty"><option value="easy">{{ t('resume.easyOption') }}</option><option value="medium">{{ t('resume.mediumOption') }}</option><option value="hard">{{ t('resume.hardOption') }}</option></select></div><div class="form-group"><label>{{ t('resume.questionCount') }}</label><select v-model.number="totalQuestions"><option :value="3">{{ t('resume.quick') }}</option><option :value="5">{{ t('resume.standard') }}</option><option :value="8">{{ t('resume.deep') }}</option></select></div></div>
        <p v-if="error" class="error form-message">{{ error }}</p><button class="btn-primary full-width" type="button" @click="handleStart" :disabled="starting">{{ starting ? t('resume.generating') : t('resume.start') }}<ArrowUpRight :size="16" /></button>
      </div>

      <div v-else class="progress-stage"><div class="stage-icon stage-pulse"><Sparkles :size="30" /></div><p class="eyebrow">03 / 03</p><h2>{{ startingTitle }}</h2><div class="progress-track"><div class="progress-fill" :style="{ width: startProgress + '%' }"></div></div><div class="progress-meta"><span>{{ startProgress }}%</span><span>{{ startTip }}</span></div></div>
    </section>
  </div>
</template>

<script setup>
import { ref, onUnmounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRouter } from 'vue-router'
import { ArrowUpRight, CheckCircle2, FileSearch, FileUp, Sparkles } from '@lucide/vue'
import { uploadResume, getResume } from '../api/resume'
import { startInterview } from '../api/interview'
import { useAiProviderStore } from '../stores/aiProvider'

const { t, tm } = useI18n(); const router = useRouter(); const providerStore = useAiProviderStore(); const step = ref(1); const file = ref(null); const targetPosition = ref('Python后端开发工程师'); const difficulty = ref('medium'); const totalQuestions = ref(5); const uploading = ref(false); const starting = ref(false); const error = ref(''); const resumeId = ref(null); const parsedContent = ref(null); const analysis = ref(null)
const progress = ref(0); const parsingTitle = ref(''); const currentTip = ref(''); let tipTimer = null; let progressTimer = null
const startProgress = ref(0); const startingTitle = ref(''); const startTip = ref(''); let startTipTimer = null; let startProgressTimer = null

function formatSize(bytes = 0) { return `${(bytes / 1024 / 1024).toFixed(2)} MB` }
function onFileChange(e) { file.value = e.target.files[0] }
function onDrop(e) { const dropped = e.dataTransfer.files[0]; if (dropped && dropped.name.toLowerCase().endsWith('.pdf')) file.value = dropped }
function messageList(key) { const value = tm(key); if (Array.isArray(value) && value.length) return value.filter(item => typeof item === 'string'); const fallback = t(key); return fallback ? [fallback] : [] }
function startTipRotation() { const tips = messageList('resume.tips'); if (!tips.length) return; currentTip.value = tips[Math.floor(Math.random() * tips.length)]; tipTimer = setInterval(() => { const next = tips[Math.floor(Math.random() * tips.length)]; if (next !== currentTip.value) currentTip.value = next }, 3000) }
function startProgressAnimation() { progress.value = 0; const stages = messageList('resume.stages'); let stageIndex = 0; progressTimer = setInterval(() => { if (progress.value < 88) progress.value += 1; const thresholds = [15, 35, 55, 72, 88]; if (stageIndex < stages.length - 1 && progress.value >= (thresholds[stageIndex] || 88)) stageIndex += 1; parsingTitle.value = stages[stageIndex] || t('resume.uploading') }, 250) }
function stopAnimations() { if (tipTimer) clearInterval(tipTimer); if (progressTimer) clearInterval(progressTimer); tipTimer = null; progressTimer = null }
function startStartingAnimation() { startProgress.value = 0; const tips = messageList('resume.startTips'); if (tips.length) { startTip.value = tips[0]; let tipIndex = 0; startTipTimer = setInterval(() => { tipIndex = (tipIndex + 1) % tips.length; startTip.value = tips[tipIndex] }, 2000) } const stages = [{ target: 30, speed: 150, title: t('resume.ready') }, { target: 60, speed: 200, title: t('resume.creating') }, { target: 85, speed: 350, title: t('resume.customizing') }, { target: 95, speed: 600, title: t('resume.startSoon') }]; let index = 0; const tick = () => { if (index >= stages.length) return; const stageData = stages[index]; if (startProgress.value < stageData.target) { startProgress.value++; startingTitle.value = stageData.title; startProgressTimer = setTimeout(tick, stageData.speed) } else { index++; tick() } }; tick() }
function stopStartingAnimation() { if (startTipTimer) clearInterval(startTipTimer); if (startProgressTimer) clearTimeout(startProgressTimer); startTipTimer = null; startProgressTimer = null }
onUnmounted(() => { stopAnimations(); stopStartingAnimation() })

async function ensureProvider() { try { await providerStore.refresh(); if (providerStore.configured) return true } catch (_) {} router.push({ path: '/settings/api', query: { required: '1' } }); return false }
async function handleUpload() { error.value = ''; if (!(await ensureProvider())) return; uploading.value = true; try { step.value = 'parsing'; parsingTitle.value = messageList('resume.stages')[0] || t('resume.uploading'); startTipRotation(); startProgressAnimation(); const data = await uploadResume(file.value, targetPosition.value); resumeId.value = data.resume_id; let retries = 0; while (retries < 120) { await new Promise(resolve => setTimeout(resolve, retries === 0 ? 400 : 1000)); const detail = await getResume(resumeId.value); if (detail.status === 'completed') { parsedContent.value = detail.parsed_content; analysis.value = detail.analysis; progress.value = 100; parsingTitle.value = t('resume.parseDone'); await new Promise(resolve => setTimeout(resolve, 350)); stopAnimations(); step.value = 2; return } if (detail.status === 'failed') throw new Error(t('resume.parsingFailed')); retries++ } throw new Error(t('resume.timeout')) } catch (e) { stopAnimations(); error.value = e.message; step.value = 1 } finally { uploading.value = false } }
function scoreColor(score) { return score >= 7 ? 'var(--success)' : score >= 5 ? 'var(--warning)' : 'var(--danger)' }
async function handleStart() { error.value = ''; if (!(await ensureProvider())) return; starting.value = true; step.value = 'starting'; startStartingAnimation(); try { const data = await startInterview({ resume_id: resumeId.value, target_position: targetPosition.value, difficulty: difficulty.value, total_questions: totalQuestions.value }); startProgress.value = 100; startingTitle.value = t('resume.prepared'); stopStartingAnimation(); await new Promise(resolve => setTimeout(resolve, 800)); router.push(`/interview/${data.interview_id}`) } catch (e) { stopStartingAnimation(); error.value = e.message; step.value = 2 } finally { starting.value = false } }
</script>

<style scoped>
.workflow-card { padding: 34px; } .step-heading { display: flex; align-items: flex-start; gap: 14px; margin-bottom: 26px; } .step-number { color: var(--text-faint); font-size: 11px; font-weight: 700; } .step-heading h2 { font-size: 22px; font-weight: 650; } .step-heading p { margin-top: 6px; color: var(--text-soft); font-size: 13px; } .step-check { margin-left: auto; color: var(--success); }
.upload-area { min-height: 190px; margin-bottom: 24px; border: 1px dashed var(--border-strong); border-radius: var(--radius-lg); display: flex; flex-direction: column; align-items: center; justify-content: center; gap: 9px; color: var(--text-soft); cursor: pointer; background: var(--bg-soft); transition: .2s ease; } .upload-area:hover { background: var(--bg-hover); border-color: var(--text-soft); } .upload-area strong { color: var(--text); font-size: 14px; } .upload-area span { color: var(--text-faint); font-size: 12px; }
.full-width { width: 100%; } .form-message { margin: -4px 0 14px; } .progress-stage { padding: 56px 12px 48px; text-align: center; } .stage-icon { width: 64px; height: 64px; margin: 0 auto 22px; display: grid; place-items: center; border-radius: 50%; color: var(--text); background: var(--bg-soft); border: 1px solid var(--border); } .stage-pulse { animation: pulse 1.8s ease-in-out infinite; } .progress-stage h2 { margin-top: 12px; font-size: 22px; font-weight: 650; } .progress-track { max-width: 520px; height: 6px; margin: 28px auto 0; overflow: hidden; border-radius: 99px; background: var(--bg-hover); } .progress-fill { height: 100%; border-radius: inherit; background: var(--primary); transition: width .3s ease; } .progress-meta { max-width: 520px; margin: 12px auto 0; display: flex; justify-content: space-between; gap: 16px; color: var(--text-faint); font-size: 12px; text-align: left; } .progress-meta span:last-child { text-align: right; }
.parsed-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; margin-bottom: 26px; } .parsed-grid > div { padding-bottom: 14px; border-bottom: 1px solid var(--border); } .parsed-grid .wide { grid-column: 1 / -1; } .parsed-grid span:first-child { display: block; margin-bottom: 7px; color: var(--text-faint); font-size: 11px; } .parsed-grid strong, .parsed-grid p { color: var(--text); font-size: 14px; line-height: 1.7; font-weight: 500; }
.tag-list { display: flex; flex-wrap: wrap; gap: 7px; } .tag { color: var(--text-soft); background: var(--bg-soft); border: 1px solid var(--border); } .analysis-panel { margin-bottom: 28px; padding: 22px; border: 1px solid var(--border); border-radius: var(--radius-md); background: var(--bg-soft); } .analysis-header { display: flex; align-items: center; justify-content: space-between; gap: 16px; } .analysis-header h3 { margin-top: 7px; font-size: 16px; } .score-badge { font-size: 30px; font-weight: 700; } .analysis-summary { margin-top: 18px; color: var(--text-soft); font-size: 13px; line-height: 1.75; } .analysis-columns { display: grid; grid-template-columns: 1fr 1fr; gap: 20px; margin-top: 20px; } .analysis-panel h4 { margin-bottom: 9px; color: var(--text-soft); font-size: 12px; font-weight: 700; } .analysis-panel ul { padding-left: 16px; color: var(--text-soft); font-size: 13px; line-height: 1.75; } .success-text { color: var(--success) !important; } .danger-text { color: var(--danger) !important; } .config-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }
@keyframes pulse { 0%, 100% { transform: scale(1); opacity: 1; } 50% { transform: scale(1.06); opacity: .65; } }
@media (max-width: 600px) { .workflow-card { padding: 24px 20px; } .parsed-grid, .analysis-columns, .config-grid { grid-template-columns: 1fr; } .parsed-grid .wide { grid-column: auto; } .progress-stage { padding: 36px 0; } .progress-meta { flex-direction: column; gap: 8px; } .progress-meta span:last-child { text-align: center; } }
</style>
